version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    revive:
      severity: error
      rules:
        - name: context-keys-type
        - name: time-naming
        - name: var-declaration
        - name: unexported-return
        - name: errorf
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
          arguments:
            - - ID
              - SQL
              - URL
              - RAM
              - RPC
            # - ["avoid-meaningless-package-names"]
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: argument-limit
          arguments:
            - 5
        - name: cyclomatic
          arguments:
            - 20
        - name: max-public-structs
          arguments:
            - 20
        - name: empty-block
        - name: superfluous-else
        - name: confusing-naming
        - name: modifies-parameter
        - name: confusing-results
        - name: deep-exit
        - name: unused-parameter
        - name: unreachable-code
        - name: flag-parameter
        - name: unnecessary-stmt
        - name: struct-tag
        - name: modifies-value-receiver
        - name: constant-logical-expr
        - name: bool-literal-in-expr
        - name: redefines-builtin-id
        - name: function-result-limit
          arguments:
            - 5
        - name: imports-blocklist
        - name: range-val-in-closure
        - name: range-val-address
        - name: waitgroup-by-value
        - name: atomic
        - name: empty-lines
        - name: line-length-limit
          arguments:
            - 140
        - name: call-to-gc
        - name: duplicated-imports
        - name: import-shadowing
        - name: bare-return
        - name: unused-receiver
        - name: unhandled-error
          arguments:
            - fmt.Printf
        - name: cognitive-complexity
          arguments:
            - 50
        - name: string-of-int
        - name: early-return
        - name: unconditional-recursion
        - name: identical-branches
        - name: defer
          arguments:
            - - call-chain
              - loop
              - method-call
              - recover
              - return
        - name: unexported-naming
        - name: function-length
          arguments:
            - 60
            - 120
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -ST1023
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gochecknoinits
          - goconst
          - lll
          - mnd
          - revive
        path: _test\.go
      - linters:
          - gosec
        path: _test\.go
        text: 'G404: Use of weak random number generator'
      - linters:
          - govet
        path: _test\.go
        text: 'shadow: declaration of'
      - linters:
          - lll
          - revive
        text: line is [\d]+ characters
        source: go:generate
      - linters:
          - lll
          - revive
        text: line is [\d]+ characters
        source: '// [@]?doc[s]?[ ]?:'
    paths:
      - deploy
      - docs
      - scripts
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vesoft-inc)
    goimports:
      local-prefixes:
        - github.com/vesoft-inc
  exclusions:
    generated: lax
    paths:
      - deploy
      - docs
      - scripts
      - third_party$
      - builtin$
      - examples$
