name: pull_request

on:
  push:
    branches: [ master, 'release-**']
  pull_request:
    branches: [ master, 'release-**']
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    name: test with nebula docker compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test importer
        run: docker-compose up --exit-code-from importer
        timeout-minutes: 20
      - name: cleanup
        if: ${{ always() }}
        run: docker-compose down -v
