name: test

on: [push, pull_request]

jobs:
  test:
    name: test with nebula docker compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test importer
        run: docker-compose up --exit-code-from importer
